// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "url": "http://www.swagger.io/support",
            "email": "support@swagger.io"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/comments": {
            "get": {
                "description": "Finds comments in the system with a paginated list with optional filters and sorting",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Comment"
                ],
                "summary": "Find comments",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Offset for pagination",
                        "name": "offset",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Limit for pagination",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter rules\u003cbr\u003e\u003cbr\u003e### Format:\u003cbr\u003e{field}:{value}:{operator}\u003cbr\u003eSupported operators: eq, lt, gt, lte, gte, in, like, is, not",
                        "name": "filter",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Sort rules\u003cbr\u003e\u003cbr\u003e### Format:\u003cbr\u003e{field}:{direction}\u003cbr\u003eSupported directions: asc, desc",
                        "name": "order",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "success",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/blog-system_internal_delivery_http_response.PaginationResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/blog-system_internal_model.GetCommentByIDRes"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "error",
                        "schema": {
                            "$ref": "#/definitions/blog-system_internal_delivery_http_response.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Creates a new comment in the system",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Comment"
                ],
                "summary": "Create a new comment",
                "parameters": [
                    {
                        "description": "Create Comment Request",
                        "name": "comment",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/blog-system_internal_model.CreateCommentReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "success",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/blog-system_internal_delivery_http_response.DataResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/blog-system_internal_model.CreateCommentRes"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "error",
                        "schema": {
                            "$ref": "#/definitions/blog-system_internal_delivery_http_response.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/comments/{id}": {
            "get": {
                "description": "Gets a comment in the system",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Comment"
                ],
                "summary": "Get a comment",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Comment ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "success",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/blog-system_internal_delivery_http_response.DataResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/blog-system_internal_model.GetCommentByIDRes"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "error",
                        "schema": {
                            "$ref": "#/definitions/blog-system_internal_delivery_http_response.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Deletes a comment in the system",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Comment"
                ],
                "summary": "Delete a comment",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Comment ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "success",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/blog-system_internal_delivery_http_response.DataResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/blog-system_internal_model.DeleteCommentRes"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "error",
                        "schema": {
                            "$ref": "#/definitions/blog-system_internal_delivery_http_response.ErrorResponse"
                        }
                    }
                }
            },
            "patch": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Updates a comment in the system",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Comment"
                ],
                "summary": "Update a comment",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Comment ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Update Comment Request",
                        "name": "comment",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/blog-system_internal_model.UpdateCommentReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "success",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/blog-system_internal_delivery_http_response.DataResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/blog-system_internal_model.UpdateCommentRes"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "error",
                        "schema": {
                            "$ref": "#/definitions/blog-system_internal_delivery_http_response.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/posts": {
            "get": {
                "description": "Finds posts in the system with a paginated list of vendors with optional filters and sorting",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Post"
                ],
                "summary": "Find posts",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Offset for pagination",
                        "name": "offset",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Limit for pagination",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter rules\u003cbr\u003e\u003cbr\u003e### Format:\u003cbr\u003e{field}:{value}:{operator}\u003cbr\u003eSupported operators: eq, lt, gt, lte, gte, in, like, is, not",
                        "name": "filter",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Sort rules\u003cbr\u003e\u003cbr\u003e### Format:\u003cbr\u003e{field}:{direction}\u003cbr\u003eSupported directions: asc, desc",
                        "name": "order",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "success",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/blog-system_internal_delivery_http_response.PaginationResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/blog-system_internal_model.GetPostByIDRes"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "error\"\t\t\t\t\t\t\t\t\t\"error",
                        "schema": {
                            "$ref": "#/definitions/blog-system_internal_delivery_http_response.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    },
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Creates a new post in the system",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Post"
                ],
                "summary": "Create a new post",
                "parameters": [
                    {
                        "description": "Create Post Request",
                        "name": "post",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/blog-system_internal_model.CreatePostReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "success",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/blog-system_internal_delivery_http_response.DataResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/blog-system_internal_model.CreatePostRes"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "error",
                        "schema": {
                            "$ref": "#/definitions/blog-system_internal_delivery_http_response.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/posts/{id}": {
            "get": {
                "description": "Gets a post in the system",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Post"
                ],
                "summary": "Get a post",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Post ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "success",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/blog-system_internal_delivery_http_response.DataResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/blog-system_internal_model.GetPostByIDRes"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "error",
                        "schema": {
                            "$ref": "#/definitions/blog-system_internal_delivery_http_response.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Deletes a post in the system",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Post"
                ],
                "summary": "Delete a post",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Post ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "success",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/blog-system_internal_delivery_http_response.DataResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/blog-system_internal_model.DeletePostRes"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "error",
                        "schema": {
                            "$ref": "#/definitions/blog-system_internal_delivery_http_response.ErrorResponse"
                        }
                    }
                }
            },
            "patch": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Updates a post in the system",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Post"
                ],
                "summary": "Update a post",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Post ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Update Post Request",
                        "name": "post",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/blog-system_internal_model.UpdatePostReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "success",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/blog-system_internal_delivery_http_response.DataResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/blog-system_internal_model.UpdatePostRes"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "error",
                        "schema": {
                            "$ref": "#/definitions/blog-system_internal_delivery_http_response.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/users/login": {
            "post": {
                "description": "Authenticates a user and returns a token",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "User login",
                "parameters": [
                    {
                        "description": "Login User Request",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/blog-system_internal_model.CreateUserReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "success",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/blog-system_internal_delivery_http_response.DataResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/blog-system_internal_model.CreateUserRes"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "error",
                        "schema": {
                            "$ref": "#/definitions/blog-system_internal_delivery_http_response.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/users/register": {
            "post": {
                "description": "Registers a new user in the system",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Register a new user",
                "parameters": [
                    {
                        "description": "Register User Request",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/blog-system_internal_model.CreateUserReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "success",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/blog-system_internal_delivery_http_response.DataResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/blog-system_internal_model.CreateUserRes"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "error",
                        "schema": {
                            "$ref": "#/definitions/blog-system_internal_delivery_http_response.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "blog-system_internal_delivery_http_response.DataResponse": {
            "type": "object",
            "properties": {
                "data": {},
                "responseCode": {
                    "type": "integer"
                },
                "responseMessage": {}
            }
        },
        "blog-system_internal_delivery_http_response.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {},
                "responseCode": {
                    "type": "integer"
                },
                "responseMessage": {}
            }
        },
        "blog-system_internal_delivery_http_response.PaginationResponse": {
            "type": "object",
            "properties": {
                "data": {},
                "pagination": {},
                "responseCode": {
                    "type": "integer"
                },
                "responseMessage": {}
            }
        },
        "blog-system_internal_entity.Comments": {
            "type": "object",
            "properties": {
                "author": {
                    "description": "relationship",
                    "allOf": [
                        {
                            "$ref": "#/definitions/blog-system_internal_entity.Users"
                        }
                    ]
                },
                "content": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "post_references_id": {
                    "type": "string"
                },
                "references_id": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "user_references_id": {
                    "type": "string"
                }
            }
        },
        "blog-system_internal_entity.Users": {
            "type": "object",
            "properties": {
                "references_id": {
                    "type": "string"
                },
                "username": {
                    "type": "string",
                    "example": "john_doe"
                }
            }
        },
        "blog-system_internal_model.CreateCommentReq": {
            "type": "object",
            "required": [
                "content",
                "post_references_id"
            ],
            "properties": {
                "content": {
                    "type": "string"
                },
                "post_references_id": {
                    "type": "string"
                },
                "user_references_id": {
                    "type": "string"
                }
            }
        },
        "blog-system_internal_model.CreateCommentRes": {
            "type": "object",
            "properties": {
                "author": {
                    "description": "relationship",
                    "allOf": [
                        {
                            "$ref": "#/definitions/blog-system_internal_entity.Users"
                        }
                    ]
                },
                "content": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "post_references_id": {
                    "type": "string"
                },
                "references_id": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "user_references_id": {
                    "type": "string"
                }
            }
        },
        "blog-system_internal_model.CreatePostReq": {
            "type": "object",
            "required": [
                "content",
                "title"
            ],
            "properties": {
                "content": {
                    "type": "string"
                },
                "published": {
                    "type": "boolean"
                },
                "tags": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "blog-system_internal_model.CreatePostRes": {
            "type": "object",
            "properties": {
                "author": {
                    "$ref": "#/definitions/blog-system_internal_entity.Users"
                },
                "comments": {
                    "description": "relationship",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/blog-system_internal_entity.Comments"
                    }
                },
                "content": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "last_published_at": {
                    "type": "string"
                },
                "published": {
                    "type": "boolean"
                },
                "references_id": {
                    "type": "string"
                },
                "tags": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "user_references_id": {
                    "type": "string"
                }
            }
        },
        "blog-system_internal_model.CreateUserReq": {
            "type": "object",
            "required": [
                "password",
                "username"
            ],
            "properties": {
                "password": {
                    "type": "string",
                    "minLength": 8,
                    "example": "SecurePass123!"
                },
                "username": {
                    "type": "string",
                    "example": "john_doe"
                }
            }
        },
        "blog-system_internal_model.CreateUserRes": {
            "type": "object",
            "properties": {
                "references_id": {
                    "type": "string"
                },
                "username": {
                    "type": "string",
                    "example": "john_doe"
                }
            }
        },
        "blog-system_internal_model.DeleteCommentRes": {
            "type": "object",
            "properties": {
                "referencesId": {
                    "description": "uuid, will be get from query handler",
                    "type": "string"
                }
            }
        },
        "blog-system_internal_model.DeletePostRes": {
            "type": "object",
            "properties": {
                "referencesId": {
                    "description": "uuid, will be get from query handler",
                    "type": "string"
                }
            }
        },
        "blog-system_internal_model.GetCommentByIDRes": {
            "type": "object",
            "properties": {
                "author": {
                    "description": "relationship",
                    "allOf": [
                        {
                            "$ref": "#/definitions/blog-system_internal_entity.Users"
                        }
                    ]
                },
                "content": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "post_references_id": {
                    "type": "string"
                },
                "references_id": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "user_references_id": {
                    "type": "string"
                }
            }
        },
        "blog-system_internal_model.GetPostByIDRes": {
            "type": "object",
            "properties": {
                "author": {
                    "$ref": "#/definitions/blog-system_internal_entity.Users"
                },
                "comments": {
                    "description": "relationship",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/blog-system_internal_entity.Comments"
                    }
                },
                "content": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "last_published_at": {
                    "type": "string"
                },
                "published": {
                    "type": "boolean"
                },
                "references_id": {
                    "type": "string"
                },
                "tags": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "user_references_id": {
                    "type": "string"
                }
            }
        },
        "blog-system_internal_model.UpdateCommentReq": {
            "type": "object",
            "required": [
                "content",
                "post_references_id"
            ],
            "properties": {
                "content": {
                    "type": "string"
                },
                "post_references_id": {
                    "type": "string"
                },
                "referencesId": {
                    "type": "string"
                },
                "user_references_id": {
                    "type": "string"
                }
            }
        },
        "blog-system_internal_model.UpdateCommentRes": {
            "type": "object",
            "properties": {
                "author": {
                    "description": "relationship",
                    "allOf": [
                        {
                            "$ref": "#/definitions/blog-system_internal_entity.Users"
                        }
                    ]
                },
                "content": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "post_references_id": {
                    "type": "string"
                },
                "references_id": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "user_references_id": {
                    "type": "string"
                }
            }
        },
        "blog-system_internal_model.UpdatePostReq": {
            "type": "object",
            "required": [
                "content",
                "title"
            ],
            "properties": {
                "content": {
                    "type": "string"
                },
                "published": {
                    "type": "boolean"
                },
                "referencesId": {
                    "type": "string"
                },
                "tags": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "blog-system_internal_model.UpdatePostRes": {
            "type": "object",
            "properties": {
                "author": {
                    "$ref": "#/definitions/blog-system_internal_entity.Users"
                },
                "comments": {
                    "description": "relationship",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/blog-system_internal_entity.Comments"
                    }
                },
                "content": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "last_published_at": {
                    "type": "string"
                },
                "published": {
                    "type": "boolean"
                },
                "references_id": {
                    "type": "string"
                },
                "tags": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "user_references_id": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    },
    "externalDocs": {
        "description": "OpenAPI",
        "url": "https://swagger.io/resources/open-api/"
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "Blog-system API",
	Description:      "This is a sample blog system.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
